2019-08-17 16:55:31,518 ERROR: Exception on /reset_password_request [POST] [in g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\Projects\FlaskMegaTutorial\app\routes.py", line 161, in reset_password_request
    send_password_reset_email(user)
  File "G:\Projects\FlaskMegaTutorial\app\email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "G:\Projects\FlaskMegaTutorial\app\models.py", line 67, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm=['HS256']).decode('utf-8')
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jwt\api_jwt.py", line 65, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jwt\api_jws.py", line 88, in encode
    if algorithm not in self._valid_algs:
TypeError: unhashable type: 'list'
2019-08-17 16:56:47,997 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:48]
2019-08-17 16:56:53,694 ERROR: Exception on /reset_password_request [POST] [in g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\Projects\FlaskMegaTutorial\app\routes.py", line 161, in reset_password_request
    send_password_reset_email(user)
  File "G:\Projects\FlaskMegaTutorial\app\email.py", line 16, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2019-08-17 16:57:18,900 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:48]
2019-08-17 16:57:24,040 ERROR: Exception on /reset_password_request [POST] [in g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\Projects\FlaskMegaTutorial\app\routes.py", line 161, in reset_password_request
    send_password_reset_email(user)
  File "G:\Projects\FlaskMegaTutorial\app\email.py", line 19, in send_password_reset_email
    'email/reset_password.txt', user=user, token=token),
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "G:\Projects\FlaskMegaTutorial\app\templates\email\reset_password.txt", line 5, in template
    {{ url_for('reset_password'), token=token, _external=True }}
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\parser.py", line 876, in subparse
    self.stream.expect('variable_end')
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\jinja2\lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
2019-08-17 16:58:03,900 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:48]
2019-08-17 16:58:20,736 ERROR: Exception on /reset_password_request [POST] [in g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Antra\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 387, in getreply
    line = self.file.readline(_MAXLINE + 1)
  File "C:\Users\Antra\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\Projects\FlaskMegaTutorial\app\routes.py", line 161, in reset_password_request
    send_password_reset_email(user)
  File "G:\Projects\FlaskMegaTutorial\app\email.py", line 21, in send_password_reset_email
    'email/reset_password.html', user=user, token=token))
  File "G:\Projects\FlaskMegaTutorial\app\email.py", line 10, in send_email
    mail.send(msg)
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "g:\projects\flaskmegatutorial\venv\lib\site-packages\flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "C:\Users\Antra\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Users\Antra\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 338, in connect
    (code, msg) = self.getreply()
  File "C:\Users\Antra\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 391, in getreply
    + str(e))
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: [WinError 10054] An existing connection was forcibly closed by the remote host
2019-08-17 16:58:34,401 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:48]
2019-08-17 17:03:39,444 INFO: Microblog startup! [in G:\Projects\FlaskMegaTutorial\app\__init__.py:48]
